services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    networks:
      postgres_network:
        aliases:
          - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_agent
    restart: always
    environment:
      TZ: ${TZ}
    volumes:
      - tg_agent_logs:/var/log/tg_agent/:rw
    networks:
      - postgres_network
    depends_on:
      postgres:
        condition: service_healthy
networks:
  postgres_network:
    driver: bridge
volumes:
  postgres_data:
    driver: local
  tg_agent_logs:
    driver: local
  static:
    external: true
    name: frontend_static
